services:
  garage:
    image: dxflrs/garage:v2.1.0
    restart: always
    ports:
      - 3900:3900
      - 3901:3901
      - 3902:3902
      - 3903:3903
    volumes:
      - ../home/galih/_data/garage.toml:/etc/garage.toml
      - ../home/galih/_data/meta:/var/lib/garage/meta
      - ../home/galih/_data/data:/var/lib/garage/data
